- project/ScalaTestPlusPlayBuild.scala
- src/main/scala/org/scalatestplus/play/AllBrowsersPerSuite.scala
- src/main/scala/org/scalatestplus/play/AllBrowsersPerTest.scala
- src/main/scala/org/scalatestplus/play/ConfiguredApp.scala
- src/main/scala/org/scalatestplus/play/ConfiguredBrowser.scala
- src/main/scala/org/scalatestplus/play/ConfiguredServer.scala
- src/main/scala/org/scalatestplus/play/MixedFixtures.scala
- src/main/scala/org/scalatestplus/play/OneAppPerSuite.scala
- src/main/scala/org/scalatestplus/play/OneAppPerTest.scala
- src/main/scala/org/scalatestplus/play/OneBrowserPerSuite.scala
- src/main/scala/org/scalatestplus/play/OneBrowserPerTest.scala
- src/main/scala/org/scalatestplus/play/OneServerPerSuite.scala
- src/main/scala/org/scalatestplus/play/OneServerPerTest.scala
- src/main/scala/org/scalatestplus/play/ServerProvider.scala
-FakeApplication -> Application refactor.
-Bump up version number for Play, ScalaTest and Selenium.
> FakeApplication -> Application Refactor + Version Upgrade

- project/ScalaTestPlusPlayBuild.scala
Bump up version of scalatest, play and selenium, now all tests passed.
> Working Play 2.4 Support

- module/project/ScalaTestPlusPlayBuild.scala
- module/src/main/scala/org/scalatestplus/play/AllBrowsersPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/AllBrowsersPerTest.scala
- module/src/main/scala/org/scalatestplus/play/ConfiguredApp.scala
- module/src/main/scala/org/scalatestplus/play/ConfiguredBrowser.scala
- module/src/main/scala/org/scalatestplus/play/ConfiguredServer.scala
- module/src/main/scala/org/scalatestplus/play/MixedFixtures.scala
- module/src/main/scala/org/scalatestplus/play/OneAppPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/OneAppPerTest.scala
- module/src/main/scala/org/scalatestplus/play/OneBrowserPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/OneBrowserPerTest.scala
- module/src/main/scala/org/scalatestplus/play/OneServerPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/OneServerPerTest.scala
- module/src/test/scala/org/scalatestplus/play/examples/oneserverpersuite/NestedExampleSpec.scala
- module/src/test/scala/org/scalatestplus/play/examples/oneserverpertest/ExampleSpec.scala
-Changed all scaladocs to use latest examples.
-Changed group and artifact ID.
> Final Touch Up

- .travis.yml
I have no idea if this will work or not due to the Selenium tests, but there's only one way to find out.
> Added travis descriptor

- build.sbt
- docs/manual/working/scalaGuide/main/tests/code/ScalaFunctionalTestSpec.scala
Same motivation like #39 has.
Also see https://github.com/playframework/playframework/pull/5786
> Explicitly depend on htmlunit 2.20 to support jQuery 2.20

- build.sbt
- project/plugins.sbt
So we can release nightly snapshots along with Play.
> Add snapshot resolvers

- build.sbt
- module/src/main/scala/org/scalatestplus/play/AllBrowsersPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/AllBrowsersPerTest.scala
- module/src/main/scala/org/scalatestplus/play/BaseOneAppPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/BaseOneAppPerTest.scala
- module/src/main/scala/org/scalatestplus/play/BaseOneServerPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/BaseOneServerPerTest.scala
- module/src/main/scala/org/scalatestplus/play/ConfiguredApp.scala
- module/src/main/scala/org/scalatestplus/play/ConfiguredBrowser.scala
- module/src/main/scala/org/scalatestplus/play/ConfiguredServer.scala
- module/src/main/scala/org/scalatestplus/play/MixedFixtures.scala
- module/src/main/scala/org/scalatestplus/play/OneAppPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/OneAppPerTest.scala
- module/src/main/scala/org/scalatestplus/play/OneBrowserPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/OneBrowserPerTest.scala
- module/src/main/scala/org/scalatestplus/play/OneServerPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/OneServerPerTest.scala
- module/src/main/scala/org/scalatestplus/play/guice/GuiceOneAppPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/guice/GuiceOneAppPerTest.scala
- module/src/main/scala/org/scalatestplus/play/guice/GuiceOneServerPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/guice/GuiceOneServerPerTest.scala
- module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithAllBrowsersPerSuiteSpec.scala
- module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithAllBrowsersPerTestSpec.scala
- module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithOneBrowserPerSuiteSpec.scala
- module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithOneBrowserPerTestSpec.scala
- module/src/test/scala/org/scalatestplus/play/examples/oneapppersuite/NestedExampleSpec.scala
- module/src/test/scala/org/scalatestplus/play/examples/onebrowserpersuite/NestedExampleSpec.scala
- module/src/test/scala/org/scalatestplus/play/examples/oneserverpersuite/NestedExampleSpec.scala
- project/build.properties
This also change some minor details:
1. Removes unnecessary imports
2. Correct some typos and documentation links
> Upgrade to Scalatest 3.0.0

- .travis.yml
- build.sbt
- docs/manual/working/scalaGuide/main/tests/code/playspec/ExampleSpec.scala
- module/src/test/scala/org/scalatestplus/play/ChromeFactorySpec.scala
- module/src/test/scala/org/scalatestplus/play/ConfiguredBrowserNestedSuite.scala
- scripts/build
- scripts/codeChecks
- scripts/runTests
- scripts/testDocumentation
This PR:
1. Improve travis configuration
2. Fix compilation problems at documentation code
3. Ignore some tests related to scalatest/scalatest#962
This PR replaces #61.
> Fix build problems

- README.md
- build.sbt
- docs/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
- docs/manual/working/scalaGuide/main/tests/code/allbrowserspersuite/ExampleOverrideBrowsersSpec.scala
- docs/manual/working/scalaGuide/main/tests/code/allbrowserspersuite/ExampleSpec.scala
- docs/manual/working/scalaGuide/main/tests/code/allbrowserspertest/ExampleSpec.scala
- docs/manual/working/scalaGuide/main/tests/code/onebrowserpersuite/ExampleSpec.scala
- docs/manual/working/scalaGuide/main/tests/code/onebrowserpertest/ExampleSpec.scala
- docs/manual/working/scalaGuide/main/tests/code/oneserverpersuite/ExampleSpec.scala
- docs/manual/working/scalaGuide/main/tests/code/oneserverpertest/ExampleSpec.scala
- docs/manual/working/scalaGuide/main/tests/code/playspec/ExampleSpec.scala
- module/src/main/scala/org/scalatestplus/play/AllBrowsersPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/AllBrowsersPerTest.scala
- module/src/test/scala/org/scalatestplus/play/MixedFixtureSpec.scala
- module/src/test/scala/org/scalatestplus/play/WsScalaTestClientSpec.scala
- module/src/test/scala/org/scalatestplus/play/examples/allbrowserspersuite/ExampleSpec.scala
- module/src/test/scala/org/scalatestplus/play/examples/allbrowserspertest/ExampleSpec.scala
- project/build.properties
- project/plugins.sbt
Cut a new version of scalatestplus-play using Play 2.6.0-M1
> Upgrade to Play 2.6.0-M1

- README.md
- build.sbt
- docs/manual/working/scalaGuide/main/tests/code/playspec/ExampleSpec.scala
- module/src/main/scala/org/scalatestplus/play/AllBrowsersPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/ChromeFactory.scala
- module/src/main/scala/org/scalatestplus/play/ConfiguredApp.scala
- module/src/main/scala/org/scalatestplus/play/ConfiguredBrowser.scala
- module/src/main/scala/org/scalatestplus/play/ConfiguredServer.scala
- module/src/main/scala/org/scalatestplus/play/PlaySpec.scala
- project/build.properties
- project/plugins.sbt
- version.sbt
Branch 2.0.x was create from tag 2.0.0-M1 (commit 5c4f161).
This PR rolls back the version to be a snapshot and also better organizes the README file.
> Better information for branch 2.0.x

- module/src/main/resources/org/scalatestplus/play/ScalaTestPlusPlayBundle.properties
- module/src/main/scala/org/scalatestplus/play/AllBrowsersPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/AllBrowsersPerTest.scala
- module/src/main/scala/org/scalatestplus/play/BrowserInfo.scala
- module/src/main/scala/org/scalatestplus/play/PhantomJSFactory.scala
- module/src/test/scala/org/scalatestplus/play/AllBrowsersPerSuiteBehaviorSpec.scala
- module/src/test/scala/org/scalatestplus/play/AllBrowsersPerTestBehaviorSpec.scala
- module/src/test/scala/org/scalatestplus/play/PhantomJSFactorySpec.scala
> Add PhantomJS support

- build.sbt
- project/plugins.sbt
> Update to Play 2.6.0

- build.sbt
- project/plugins.sbt
> Update play 2.6.2

- .travis.yml
- README.md
- build.sbt
- module/src/main/scala/org/scalatestplus/play/FirefoxFactory.scala
- module/src/test/scala/org/scalatestplus/play/AllBrowsersPerSuiteBehaviorSpec.scala
- module/src/test/scala/org/scalatestplus/play/AllBrowsersPerTestBehaviorSpec.scala
- project/build.properties
- project/plugins.sbt
> Update Play and other dependencies

- .travis.yml
- README.md
- build.sbt
- module/src/main/scala/org/scalatestplus/play/FirefoxFactory.scala
- module/src/test/scala/org/scalatestplus/play/AllBrowsersPerSuiteBehaviorSpec.scala
- module/src/test/scala/org/scalatestplus/play/AllBrowsersPerTestBehaviorSpec.scala
- project/build.properties
- project/plugins.sbt
> [3.1.x]: Update Play and other dependencies (#105)

- build.sbt
- module/src/main/scala/org/scalatestplus/play/BaseOneAppPerTest.scala
- module/src/main/scala/org/scalatestplus/play/BaseOneServerPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/BaseOneServerPerTest.scala
related to https://github.com/playframework/playframework/pull/8963
related to https://github.com/playframework/play-grpc/pull/33
> Honour user's choice of ServerProvider

- .travis.yml
- build.sbt
- module/src/main/scala/org/scalatestplus/play/InternetExplorerFactory.scala
- module/src/main/scala/org/scalatestplus/play/MixedFixtures.scala
- module/src/main/scala/org/scalatestplus/play/Resources.scala
- module/src/main/scala/org/scalatestplus/play/SafariFactory.scala
- module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithAllBrowsersPerSuiteSpec.scala
- module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithAllBrowsersPerTestSpec.scala
- module/src/test/scala/org/scalatestplus/play/EventRecordingReporter.scala
- module/src/test/scala/org/scalatestplus/play/OneServerPerTestWithAllBrowsersPerSuiteSpec.scala
- module/src/test/scala/org/scalatestplus/play/OneServerPerTestWithAllBrowsersPerTestSpec.scala
- module/src/test/scala/org/scalatestplus/play/SilentReporter.scala
Needs to be backported to 4.0.x.
> Support Scala 2.13.0-M5

- build.sbt
- project/plugins.sbt
- scripts/validateCode
This will likely fail until the artifacts are synced to Maven central.
> [4.0.x]: Configure mima for 4.0.0 release

- scripts/validateCode
It is already cross running following Travis scala versions.
> No need to cross run mima

- .travis.yml
- build.sbt
- scripts/build
The build in travis is repeating the same `SCRIPT` (`sbt test`) instead of using the configured in the appropriate axis of the build matrix. 
See https://travis-ci.com/playframework/scalatestplus-play/builds/106790168, and in particular see https://travis-ci.com/playframework/scalatestplus-play/jobs/189765082#L548 which invokes `sbt test` instead of `sbt validateDocs`.
Supersedes #146 (was PR'ing from a fork)
> Fix travis setup

- project/plugins.sbt
> [4.0.x]: Add snapshot repositories

- .travis.yml
- build.sbt
- module/src/test/scala/org/scalatestplus/play/OneServerPerTestComponentSynchronizationSpec.scala
- project/plugins.sbt
- version.sbt
> Play 2.8.0-M1

- .travis.yml
- build.sbt
- project/plugins.sbt
> [master]: ﻿Support Scala 2.13

- project/plugins.sbt
Refs https://github.com/lightbend/mima/issues/422
> Workaround MiMa resolver

- .travis.yml
- scripts/run-ci
> Consolidate Travis CI jobs

- .travis.yml
- build.sbt
- module/src/main/scala/org/scalatestplus/play/ConfiguredServer.scala
- project/build.properties
- project/plugins.sbt
Also updates:
- sbt to 1.3.4
- interplay to 2.1.3
> Use Play 2.8.0-RC2

- build.sbt
This might make upgrading scalatest easier later
> Update mockito to 3.2.4

- .github/settings.yml
- .mergify.yml
- .scalafmt.conf
> [5.0.x] Rename master branch to main

- build.sbt
- project/plugins.sbt
> Play 2.9.0-M3

- module/src/main/scala/org/scalatestplus/play/MixedFixtures.scala
Avoids duplicated and some not so nice code.
> Refactoring

- build.sbt
- docs/manual/working/scalaGuide/main/tests/code/ScalaFunctionalTestSpec.scala
- module/src/main/scala/org/scalatestplus/play/BaseOneServerPerSuite.scala
- module/src/main/scala/org/scalatestplus/play/BaseOneServerPerTest.scala
- module/src/main/scala/org/scalatestplus/play/MixedFixtures.scala
Part of https://github.com/playframework/playframework/issues/5473
> Support random port

- build.sbt
- module/src/test/scala/org/scalatestplus/play/ConfiguredAppSpec.scala
- module/src/test/scala/org/scalatestplus/play/ConfiguredServerSpec.scala
- module/src/test/scala/org/scalatestplus/play/ConfiguredServerWithConfiguredBrowserSpec.scala
- module/src/test/scala/org/scalatestplus/play/OneServerPerSuiteWithConfiguredBrowserSpec.scala
- module/src/test/scala/org/scalatestplus/play/OneServerPerTestWithConfiguredBrowserSpec.scala
- same as https://github.com/playframework/playframework/pull/12029
> remove "-Xmigration"

- build.sbt
> [6.0.x] selenium-java 4.14.1 / htmlunit-driver 4.13.0

- module/src/main/scala/org/scalatestplus/play/ServerProvider.scala
- module/src/main/scala/org/scalatestplus/play/WsScalaTestClient.scala
> [6.0.x] https improvements

- build.sbt
Reverts playframework/scalatestplus-play#499
> Revert "[6.0.x] selenium-java 4.19.0 (was 4.14.1)"

- build.sbt
- project/plugins.sbt
Needed to enable scripted tests again, see https://github.com/playframework/playframework/commit/083ea67fbd1738a0d717fff3749e7c10c604aa7c
> Play 3.1.0-M1 (guice 7 / jakarta.inject) + Scala 2.13.16
