playframework/scalatestplus-play

build.sbt, docs/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md, docs/manual/working/scalaGuide/main/tests/ScalaTestingWithScalaTest.md, project/plugins.sbt
* The ScalaFunctionalTestingWithScalaTest wasn't copied from the Play docs.
* Updated the scaladoc links to point to the scaladocs published with Play.
* Updated to new PlayDocs plugin that allows adding the ScalaTest scaladocs to running/validating the docs.
* Fixed broken link to Play docs.
=> Fixed up docs

project/ScalaTestPlusPlayBuild.scala, src/main/scala/org/scalatestplus/play/MixedFixtures.scala, src/test/scala/org/scalatestplus/play/MixedFixtureSpec.scala, src/test/scala/org/scalatestplus/play/SilentReporter.scala
Changed App, Server, HtmlUnit, Firefox, Chrome, Safari and InternetExplorer in MixedFixtures to create Application instance lazily.  This helps to delay creation of Application instance from test registration to test execution.
=> Lazy MixedFixtures

module/src/main/scala/org/scalatestplus/play/MixedFixtures.scala, module/src/test/scala/org/scalatestplus/play/MixedFixtureSpec.scala, module/src/test/scala/org/scalatestplus/play/SilentReporter.scala
Changed App, Server, HtmlUnit, Firefox, Chrome, Safari and InternetExplorer in MixedFixtures to create Application instance lazily, this delays the creation of passed in Application from test registration to test execution.
=> Lazy MixedFixtures for Master

docs/manual/working/scalaGuide/main/tests/code/ScalaFunctionalTestSpec.scala, docs/manual/working/scalaGuide/main/tests/code/oneserverpersuite/ExampleSpec.scala, docs/manual/working/scalaGuide/main/tests/code/oneserverpertest/ExampleSpec.scala, module/src/main/scala/org/scalatestplus/play/WsScalaTestClient.scala
WS.client is deprecated, so let's make an implicit WSClient available.  
It's not possible to add two overloads with implicits because it's ambiguous, so the default is to use WS.client for the implicit argument.
=> Add option for taking WSClient to help with 2.5.x deprecation.

module/src/main/scala/org/scalatestplus/play/WsScalaTestClient.scala, module/src/test/scala/org/scalatestplus/play/MixedFixturesWsScalaTestClientSpec.scala, module/src/test/scala/org/scalatestplus/play/WsScalaTestClientSpec.scala
Remove the implicit WS.client default parameter from WsScalaTestClient.  
Use of the default is problematic in 2.5.x since WS is deprecated, and will not compile at all against Play 2.6.x as the class does not exist.  
Also, vegemite tries to compile scalatestplus-play as part of the nightly build and use it against 2.6.x -- so this will fix the nightly build as well.
=> Update the WsScalaTestClient for no implicit WS.

build.sbt
when I use `GuiceOneServerPerSuite` with play-2.6-RC2, it cause this error.
```
[info]   java.lang.NoClassDefFoundError: play/core/server/ServerWithStop
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[info]   at …
```
=> update play version to 2.6-RC2

module/src/main/scala/org/scalatestplus/play/components/WithApplicationComponents.scala, module/src/test/scala/org/scalatestplus/play/OneServerPerTestComponentShutdownSpec.scala
When context is shared between tests then stopHook is not executed
after each test, this started to happen since upgrade to Play 2.7 and ScalaTest+ 4.0.0
=> Change context to def to fix shutdown

module/src/main/scala/org/scalatestplus/play/BaseOneServerPerTest.scala, module/src/test/scala/org/scalatestplus/play/OneServerPerTestComponentSynchronizationSpec.scala
`BaseOneServerPerTest` in combination with mixins which have lazy vals can result in deadlock when asynchronous test is executed. I encountered such issue in my project for following assertion:
```scala
"some string".mustNot(equal("other string"))
```
after upgrade  to Play 2.7 and ScalaTest+ 4.0.1
=> Prevent deadlock when BaseOneServerPerTest is used

.travis.yml
Backporting #143 to `4.0.x` I broke the branch in Travis (or surfaced the fact that the build was broken on that branch, depends on how you look at it).
=> Manually backporting bits and pieces from #180

docs/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
When reading the docs about testing on playframework.com, it was not directly obvious to me that `inMemoryDatabase` is a member of the `Helpers` object. Even though the doc page technically says:
> Most of these can be found either in the play.api.test package or in the Helpers object
at the top of the page, I still think it is helpful to be explicit here, close to the code snippet.
=> Clarify docs about testing models

README.md, build.sbt, docs/manual/working/scalaGuide/main/tests/ScalaTestingWithScalaTest.md, docs/manual/working/scalaGuide/main/tests/code/ExampleMockitoSpec.scala, docs/manual/working/scalaGuide/main/tests/code/UserServiceSpec.scala
- Add scalatest plus mockito as a dependency.
- Fix docs accordingly.
- Fix brokenn link to travis at the first page.
=> Add scalatest plus mockito as a dependency.

.github/settings.yml, .github/workflows/release-drafter.yml, .scalafmt.conf, RELEASING.md
@SethTisue and @ihostage already renamed the `master` branch in some play repos:
* https://github.com/playframework/cachecontrol/pull/163
* https://github.com/playframework/play-file-watch/pull/136
* https://github.com/playframework/play-json/pull/598
* https://github.com/playframework/play-soap/pull/282
* https://github.com/playframework/play-ws/pull/597
* https://github.com/playframework/twirl/pull/416
Now that we are centralising configs in the [`.github`](https://github.com/playframework/.github) repo it's a good idea that all repos have the same default branch name.
To change to `main` locally (if the remote to this repo is called `upstream`):
```sh
git branch -m master main # rename master to main (actually "move")
git fetch upstream
git branch -u upstream/main main # set upstream …
```
=> Rename master branch to main

docs/manual/working/scalaGuide/main/tests/code/ScalaFunctionalTestSpec.scala
Many of the code samples in [ScalaFunctionalTestingWithScalaTest](https://www.playframework.com/documentation/2.8.x/ScalaFunctionalTestingWithScalaTest) use the Helpers implicitly and it would be helpful to include it in the import list as with the [ScalaFunctionalTestingWithSpecs2](https://www.playframework.com/documentation/2.8.x/ScalaFunctionalTestingWithSpecs2) page
=> Add wildcard import for Helpers in ScalaFunctionalTestSpec

build.sbt, docs/manual/working/scalaGuide/main/tests/code/ScalaFunctionalTestSpec.scala, module/src/main/scala/org/scalatestplus/play/MixedFixtures.scala, project/build.properties, project/plugins.sbt
#418 was a bit dirty. E.g. there is no need to rename the port variable.
Also, Play 2.9 latest milestone itself now by defaults uses random ports, so we can make use of that and the `runningWithPort` helper method.
=> Upgrade Play: Random ports by default, provides better helpers

docs/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
=> A random port is used now

build.sbt, project/Omnidoc.scala, project/Playdoc.scala, project/plugins.sbt
As part of https://github.com/playframework/interplay/issues/150
=> Drop interplay

module/src/main/scala/org/scalatestplus/play/ServerProvider.scala, module/src/main/scala/org/scalatestplus/play/WsScalaTestClient.scala
We fallback to https port in the play-testkit already, we need the same here.
See
- https://github.com/playframework/playframework/pull/11843
- https://github.com/playframework/playframework/blob/f74c2340962b69b389e89c67a30aa474aa6a1958/transport/server/play-server/src/main/scala/play/core/server/Server.scala#L249
Also we need to construct https urls.
All this is needed for
- https://github.com/playframework/play-grpc/pull/479
=> https improvements

build.sbt
Reverts playframework/scalatestplus-play#476
main is still the stable branch for the 7.0.x release, we did not create a 7.0.x branch yet. 
For now I never upgraded beyond 4.14.1 now, see https://github.com/playframework/playframework/pull/12371#issuecomment-1970655278
=> Revert "selenium-java 4.15.0 (was 4.14.1)"

build.sbt
avoid `"org.scalatest" %% "scalatest"` for reduce unnecessary dependency.
https://www.scalatest.org/release_notes/3.2.0
=> Update scalatest dependency settings

build.sbt, module/src/main/scala/org/scalatestplus/play/AllBrowsersPerSuite.scala, module/src/main/scala/org/scalatestplus/play/AllBrowsersPerTest.scala, module/src/main/scala/org/scalatestplus/play/BaseOneAppPerSuite.scala, module/src/main/scala/org/scalatestplus/play/BaseOneAppPerTest.scala, module/src/main/scala/org/scalatestplus/play/BaseOneServerPerSuite.scala, module/src/main/scala/org/scalatestplus/play/BaseOneServerPerTest.scala, module/src/main/scala/org/scalatestplus/play/ConfiguredBrowser.scala, module/src/main/scala/org/scalatestplus/play/OneBrowserPerSuite.scala, module/src/main/scala/org/scalatestplus/play/OneBrowserPerTest.scala
https://docs.scala-lang.org/scala3/book/types-intersection.html
prepare latest Scala 3.x
```
Welcome to Scala 3.6.4 (21.0.6, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
scala> trait A; trait B
// defined trait A
// defined trait B
scala> def x: A with B = ???
1 warning found
-- [E003] Syntax Warning: ------------------------------------------------------
1 |def x: A with B = ???
|         ^^^^
|         with as a type operator has been deprecated; use & instead
|
| longer explanation available when compiling with `-explain`
def x: A & B
scala> def x: A & B = ???
def x: A & B
```
=> use new intersection type syntax

build.sbt, project/build.properties, project/plugins.sbt
Need to publish a new milestone to make 
- https://github.com/playframework/play-samples/pull/835
work.
Because of
```
[error]         * org.scala-lang.modules:scala-parser-combinators_2.13:2.4.0 (early-semver) is selected over 1.1.2
[error]             +- org.playframework:play_2.13:3.1.0-M2-573139bb-SNAPSHOT (depends on 2.4.0)
[error]             +- org.playframework:cachecontrol_2.13:3.1.0-M1       (depends on 1.1.2)
```
:point_down: 
```
+-org.scalatestplus.play:scalatestplus-play_3:8.0.0-M1 // then update to 3.1.0-M2 and release
+-org.playframework:play-ahc-ws_3:3.1.0-M1  // need to release M2 (in progress)
+-org.playframework:play-ahc-ws-standalone_3:3.1.0-M4  // needs to be  3.1.0-M6
| +-org.playframework:cachecontrol_3:3.1.0-M1
```
=> sbt-ci-release 1.11.1
